### ISSUE TITLE
windows 11/permissions 0.3.0 | error: cannot find value *value* in crate libc

### ISSUE THREAD

**Issue by collynwalte** [marcospb19/unix_file_permissions#2]
I ran my program after importing permissions with `use permissions::*;`  (didn't use it) and got a bunch of errors (E0425 and E0412) when it tried to compile. 

errors (re-worded for simplicity):

1. functions.rs:47:35 `access_syscall(&parent, libc::W_OK)` value W_OK not found in libc crate [E0425]
2. functions.rs:82:35 `access_syscall(&parent, libc::W_OK)` value W_OK not found in libc crate [E0425]
3. functions.rs:107:42 `access_syscall(&path.as_ref(), libc::R_OK)` value R_OK not found in libc crate [E0425]
4. functions.rs:132:42 `access_syscall(&path.as_ref(), libc::W_OK)` value W_OK not found in libc crate [E0425]
5. functions.rs:161:42 `access_syscall(&path.as_ref(), libc::X_OK)` value X_OK not found in libc crate [E0425]
6. functions.rs:233:48 `buf_ptr = buf.as_ptr() as *const libc::c_wchar_t;` type c_wchar_t not found in libc crate [E0412]

**Comment by marcospb19** [comment]
Thanks for the report, in the README.md there is a cross platform notice:

![image](https://user-images.githubusercontent.com/38900226/186594491-df62e87c-6a61-439a-a1f2-db27c38625f9.png)

Sadly I still cannot test this in a Windows environment, so I don't know how to fix it.

Well, now at least I know it does not compile in Windows, so I can update the documentation to explain this.

Please keep this issue open while we wait for someone to attempt to solve this.

**Comment by collynwalte** [comment]
I am new to rust, so this is probably not the best way to do it, but I got it to compile on windows. 

manually set the consts at the top of functions.rs:
```
#[cfg(target_os = "windows")]
const X_OK: c_int = 1;
#[cfg(target_os = "windows")]
const W_OK: c_int = 2;
#[cfg(target_os = "windows")]
const R_OK: c_int = 4;

#[cfg(not(target_os = "windows"))]
const X_OK: c_int = libc::X_OK;
#[cfg(not(target_os = "windows"))]
const W_OK: c_int = libc::W_OK;
#[cfg(not(target_os = "windows"))]
const R_OK: c_int = libc::R_OK;
```

and at the top of `mod tests` in functions.rs:

```
#[cfg(target_os = "windows")]
const F_OK: c_int = 0;

#[cfg(not(target_os = "windows"))]
const F_OK: c_int = libc::F_OK;
```

replace the references to libc::F/X/W/R_OK with F/X/W/R_OK:
access_syscall(&parent, libc::W_OK) becomes access_syscall(&parent, W_OK)

I would get a file not found error if a relative path didn't have "./" before it:
`is_writable("Cargo.toml")` -> error
`is_writable("./Cargo.toml")` -> true

so I added:
```
let pbuf = PathBuf::from("./").join(path.to_path_buf());
let new_path = pbuf.as_path();
```
and put a if statement for `path.is_relative()` to figure out if it should use `path` or `new_path` in the buf.extend function.

**Comment by vrmiguel** [comment]
@collynwalte Can you check if [this branch](https://github.com/vrmiguel/permissions/tree/better-windoze-support) solves the problems you're having?

**Comment by collynwalte** [comment]
`is_readable`, `is_writable`, and `is_removable` work, but since `is_executable` is [only defined on unix](https://github.com/vrmiguel/permissions/blob/better-windoze-support/src/functions.rs#L148), `cargo test` fails.
Adding `pub const X_OK: libc::c_int = 01` to the top and declaring `is_executable` for all systems results in:
```
thread 'functions::tests::test_access_syscall' panicked at 'assertion failed: !access_syscall(\"src/lib.rs\", X_OK).unwrap()', src\functions.rs:250:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I haven't troubleshooted it yet.
